# Generated by Django 2.0.3 on 2018-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.NullBooleanField()),
                ('phone', models.CharField(max_length=20, null=True)),
                ('other', models.TextField(null=True)),
            ],
        ),
    ]
