# Generated by Django 2.0.3 on 2018-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')]),
        ),
    ]
