# Generated by Django 2.0.3 on 2018-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20180424_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerinfo',
            options={'verbose_name': '管理员信息', 'verbose_name_plural': '管理员信息'},
        ),
        migrations.RemoveField(
            model_name='managerinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='managerinfo',
            name='username',
            field=models.CharField(default='test', max_length=20, unique=True, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='managerinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='managerinfo',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='其它'),
        ),
        migrations.AlterField(
            model_name='managerinfo',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='managerinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码'),
        ),
    ]
