# Generated by Django 2.0.3 on 2018-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_auto_20180425_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
