# Generated by Django 2.0.3 on 2018-04-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_auto_20180425_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerinfo',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员信息'},
        ),
    ]
