# Generated by Django 2.0.3 on 2018-04-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20180425_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attituderecord',
            name='report_reason',
            field=models.IntegerField(choices=[(0, '广告或垃圾信息'), (1, '低俗或色情'), (2, '违反相关法律法规或管理规定'), (3, '辱骂或不友善'), (4, '引战或过于偏激的主观判断'), (5, '泄露他人隐私'), (6, '与作品或讨论区主题无关'), (7, '刷屏'), (8, '其它原因')], null=True),
        ),
    ]
