# Generated by Django 2.0.3 on 2018-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20180501_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
